// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TableHelper.Infrastructure.Database.Context;

#nullable disable

namespace TableHelper.Infrastructure.Migrations
{
    [DbContext(typeof(TableHelperContext))]
    partial class TableHelperContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("TableHelper.Infrastructure.Database.Models.XwnNpc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgeDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultDealOutcome")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("InitialManner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MostObviousCharacterTrait")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TheirBackground")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TheirBiggestProblem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TheirGreatestDesire")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TheirHook")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TheirMotivation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TheirPower")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TheirRoleInSociety")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TheirWant")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FirstName");

                    b.HasIndex("Gender");

                    b.HasIndex("Surname");

                    b.ToTable("XwnNpcs");
                });
#pragma warning restore 612, 618
        }
    }
}
