networks:
  tablehelper_net:
services:
  tablehelper.api:
    image: tablehelper.api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - table_helper:./database

volumes:
  table_helper: