@TableHelper.Api_HostAddress = https://localhost:7042/api

POST https://localhost:7042/api/XwnGenerators/
Accept: application/json
Content-Type: application/json

{
  "type": "Npc",
  "npcGenerationRequest": {
    "npcsToGenerate": 1,
    "preferredNameGender": "Male",
    "preferredNameOrigin": "English"
  }
}

###
