### POST Generate NPC
< {%
    request.variables.set("npcsToGenerate", 2)
%}
POST {{base_url}}/XwnGenerators/
Accept: application/json
Content-Type: application/json

{
  "type": "Npc",
  "npcGenerationRequest": {
    "npcsToGenerate": {{npcsToGenerate}},
    "preferredNameGender": "Male",
    "preferredNameOrigin": "English"
  }
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
        const isSuccessful = jsonPath(response.body, "$.isSuccessful")
        client.assert(isSuccessful, "true");
        const npcInfo = jsonPath(response.body, "$.npcInfo")

        client.assert(npcInfo.length, 2);
    });
%}

### POST Generate Adventure Seeds
POST {{base_url}}/XwnGenerators/
Accept: application/json
Content-Type: application/json

{
  "type": "AdventureSeed",
  "adventureSeedGenerationRequest": {
    "numberOfSeeds": 2
  }
}

> {%
    client.test("Request executed successfully", function () {
        const isSuccessful = jsonPath(response.body, "$.isSuccessful")
        client.assert(isSuccessful, "true");
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


### POST Generate Patrons
POST {{base_url}}/XwnGenerators/
Accept: application/json
Content-Type: application/json

{
  "type": "Patron",
  "patronGenerationRequest": {
    "patronsToGenerate": 2
  }
}

> {%
    client.test("Request executed successfully", function () {
        const isSuccessful = jsonPath(response.body, "$.isSuccessful")
        client.assert(isSuccessful, "true");
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### POST Generate Problems
POST {{base_url}}/XwnGenerators/
Accept: application/json
Content-Type: application/json

{
  "type": "Problem",
  "problemGenerationRequest": {
    "numberOfProblems": 2
  }
}

> {%
    client.test("Request executed successfully", function () {
        const isSuccessful = jsonPath(response.body, "$.isSuccessful")
        client.assert(isSuccessful, "true");
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### POST Generate Urban Encounters
POST {{base_url}}/XwnGenerators/
Accept: application/json
Content-Type: application/json

{
  "type": "UrbanEncounter",
  "UrbanEncounterGenerationRequest": {
    "encountersToGenerate": 2
  }
}

> {%
    client.test("Request executed successfully", function () {
        const isSuccessful = jsonPath(response.body, "$.isSuccessful")
        client.assert(isSuccessful, "true");
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### POST Generate Wilderness Encounters
POST {{base_url}}/XwnGenerators/
Accept: application/json
Content-Type: application/json

{
  "type": "WildernessEncounter",
  "wildernessEncounterGeneratorRequest": {
    "encountersToGenerate": 2
  }
}

> {%
    client.test("Request executed successfully", function () {
        const isSuccessful = jsonPath(response.body, "$.isSuccessful")
        client.assert(isSuccessful, "true");
        client.assert(response.status === 200, "Response status is not 200");
    });
%}