### POST Save XWN NPCs
POST {{base_url}}/xwn/XwnNpc
Accept: application/json
Content-Type: application/json

{
  "npc": {
    "firstName": "First",
    "surname": "Last",
    "gender": "Male",
    "initialManner": "Initial",
    "defaultDealOutcome": "Deal",
    "theirMotivation": "Motivation",
    "theirWant": "Want",
    "theirPower": "Power",
    "theirHook": "Hook",
    "theirBackground": "background",
    "theirRoleInSociety": "role",
    "theirBiggestProblem": "problem",
    "ageDescription": "age",
    "theirGreatestDesire": "desire",
    "mostObviousCharacterTrait": "trait"
  }
}

### GET all NPCs 
GET {{base_url}}/xwn/XwnNpc
Content-Type: application/json

### GET a specific NPC 
GET {{base_url}}/xwn/XwnNpc/1
Content-Type: application/json

### DELETE a specific NPC 
DELETE {{base_url}}/xwn/XwnNpc/2
Content-Type: application/json